In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import networkx as nx
import scanpy as sc

import rpy2 as rp
import rpy2.robjects as ro
from rpy2.robjects import pandas2ri
import pyreadr

import os
import time
import h5py
# import mmdet
import scanpy
# import ssam
import pickle
import random
# import pyarrow
import dgl
import ast

from tqdm import tqdm

from datetime import datetime

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, recall_score, precision_score, f1_score, accuracy_score, matthews_corrcoef, mean_squared_error

# from captum.attr import IntegratedGradients
# from captum.attr import LayerConductance
# from captum.attr import NeuronConductance

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torch.nn.functional as F

# import torch_geometric

from torch.autograd import Variable
from torch.utils.data import Dataset, DataLoader, TensorDataset
from torchvision import transforms, utils

from skimage import io
from skimage import img_as_float
from scipy import ndimage

# from ssam.utils import corr, calc_ctmap, calc_corrmap, flood_fill, calc_kde
from scipy.spatial.distance import cdist

from collections import OrderedDict

from packaging import version
import subprocess

import anndata2ri
import sys
print(sys.executable)

/opt/conda/bin/python

In [2]:
# df_a = pd.DataFrame([[1, 2, 3], [4, 5, 6]])
# df_b = pd.DataFrame([[7, 8, 9], [10, 11, 12]])

# df_c = df_a.T.dot(df_b)
# df_d = df_a.dot(df_b.T)
# df_c_ = df_b.T.dot(df_a)
# df_d_ = df_b.dot(df_a.T)

# np_a = df_a.to_numpy()
# np_b = df_b.to_numpy()

# df_c = np.matmul(np_a.T,np_b)
# df_d = np.matmul(np_a,np_b.T)
# df_c_ = np.matmul(np_b.T,np_a)
# df_d_ = np.matmul(np_b,np_a.T)

<h1>Take Matrix

In [3]:
# read from rds
mat_151507 = pyreadr.read_r('dataset/df_logcount_507.rds')
mat_151672 = pyreadr.read_r('dataset/df_logcount_672.rds')
mat_151673 = pyreadr.read_r('dataset/df_logcount_673.rds')
spat_507 = np.load('dataset/datapoints/com4m_encoded_507_unfil.npy') 
spat_672 = np.load('dataset/datapoints/com4m_encoded_672_unfil.npy') 
spat_673 = np.load('dataset/datapoints/com4m_encoded_673_unfil.npy')

In [4]:
spat_507.shape

(33538, 1, 4226)

In [4]:
spat_507.shape

(33538, 1, 1000)

In [5]:
# dict to dataframe
df_151507 = mat_151507[None]
df_151672 = mat_151672[None]
df_151673 = mat_151673[None]
combined_507_672 = pd.concat([df_151507,df_151672],axis=1)
combined_all = pd.concat([combined_507_672,df_151673],axis=1)

In [6]:
df_spat507 = pd.DataFrame(spat_507.reshape((spat_507.shape[0],spat_507.shape[-1])))
df_spat672 = pd.DataFrame(spat_672.reshape((spat_672.shape[0],spat_672.shape[-1])))
df_spat673 = pd.DataFrame(spat_673.reshape((spat_673.shape[0],spat_673.shape[-1])))

In [7]:
df_spat507.shape

(33538, 1000)

In [8]:
df_spat507

,0,1,2,3,4,5,6,7,8,9,...,990,991,992,993,994,995,996,997,998,999
0,0.497674,0.498961,0.502245,0.499521,0.496613,0.501115,0.502413,0.501951,0.502810,0.495810,...,0.498094,0.499148,0.497700,0.502235,0.498503,0.498748,0.496049,0.496207,0.499636,0.500932
1,0.497699,0.499076,0.502257,0.499584,0.496634,0.501200,0.502514,0.501957,0.502721,0.495891,...,0.498079,0.499123,0.497739,0.502167,0.498533,0.498829,0.496105,0.496262,0.499720,0.501083
2,0.497699,0.499076,0.502257,0.499584,0.496634,0.501200,0.502514,0.501957,0.502721,0.495891,...,0.498079,0.499123,0.497739,0.502167,0.498533,0.498829,0.496105,0.496262,0.499720,0.501083
3,0.497699,0.499076,0.502257,0.499584,0.496634,0.501200,0.502514,0.501957,0.502721,0.495891,...,0.498079,0.499123,0.497739,0.502167,0.498533,0.498829,0.496105,0.496262,0.499720,0.501083
4,0.497655,0.498901,0.502229,0.499483,0.496600,0.501063,0.502367,0.501935,0.502830,0.495764,...,0.498090,0.499142,0.497682,0.502257,0.498486,0.498716,0.496011,0.496167,0.499602,0.500858
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33533,0.497699,0.499076,0.502257,0.499584,0.496634,0.501200,0.502514,0.501957,0.502721,0.495891,...,0.498079,0.499123,0.497739,0.502167,0.498533,0.498829,0.496105,0.496262,0.499720,0.501083
33534,0.497699,0.499076,0.502257,0.499584,0.496634,0.501200,0.502514,0.501957,0.502721,0.495891,...,0.498079,0.499123,0.497739,0.502167,0.498533,0.498829,0.496105,0.496262,0.499720,0.501083
33535,0.497680,0.498984,0.502249,0.499538,0.496619,0.501134,0.502435,0.501953,0.502794,0.495830,...,0.498093,0.499144,0.497712,0.502220,0.498508,0.498762,0.496060,0.496219,0.499652,0.500968
33536,0.497699,0.499076,0.502257,0.499584,0.496634,0.501200,0.502514,0.501957,0.502721,0.495891,...,0.498079,0.499123,0.497739,0.502167,0.498533,0.498829,0.496105,0.496262,0.499720,0.501083
33537,0.497673,0.498953,0.502243,0.499522,0.496611,0.501111,0.502413,0.501949,0.502812,0.495801,...,0.498093,0.499143,0.497700,0.502238,0.498500,0.498746,0.496049,0.496207,0.499633,0.500926

In [9]:
tots = df_151507.shape[1] + df_151672.shape[1] + df_151673.shape[1]
tots

11880

In [24]:
df_151507.T

rownames,ENSG00000243485,ENSG00000237613,ENSG00000186092,ENSG00000238009,ENSG00000239945,ENSG00000239906,ENSG00000241599,ENSG00000236601,ENSG00000284733,ENSG00000235146,...,ENSG00000277196,ENSG00000277630,ENSG00000278384,ENSG00000278633,ENSG00000276345,ENSG00000277856,ENSG00000275063,ENSG00000271254,ENSG00000277475,ENSG00000268674
AAACAACGAATAGTTC-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACAAGTATCTCCCA-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACAATCTACTAGCA-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACACCAATAACTGC-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AAACAGCTTTCAGAAG-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTGTTGTGTGTCAAGA-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TTGTTTCACATCCAGG-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TTGTTTCATTAGTCTA-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TTGTTTCCATACAACT-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TTGTTTGTGTAAATTC-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [40]:
np.array_equal(df_151507.T.values,df_151507.T.to_numpy())

True

In [29]:
np_151507 = df_151507.T.to_numpy()
np_spat507 = df_spat507.to_numpy()
print(np_151507.shape)
print(np_spat507.shape)

(4226, 33538)
(33538, 1000)

In [43]:
np_res507 = np.matmul(df_151507.T.values,df_spat507.values)
np_res672 = np.matmul(df_151672.T.values,df_spat672.values)
np_res673 = np.matmul(df_151673.T.values,df_spat673.values)

In [44]:
df_res507 = pd.DataFrame(np_res507)
df_res672 = pd.DataFrame(np_res672)
df_res673 = pd.DataFrame(np_res673)

In [45]:
df_res507.index = df_151507.columns
df_res672.index = df_151672.columns
df_res673.index = df_151673.columns

In [46]:
df_res507.T

,AAACAACGAATAGTTC-1,AAACAAGTATCTCCCA-1,AAACAATCTACTAGCA-1,AAACACCAATAACTGC-1,AAACAGCTTTCAGAAG-1,AAACAGGGTCTATATT-1,AAACAGTGTTCCTGGG-1,AAACATTTCCCGGATT-1,AAACCACTACACAGAT-1,AAACCCGAACGAAATC-1,...,TTGTGTATGCCACCAA-1,TTGTGTTTCCCGAAAG-1,TTGTTAGCAAATTCGA-1,TTGTTCAGTGTGCTAC-1,TTGTTCTAGATACGCT-1,TTGTTGTGTGTCAAGA-1,TTGTTTCACATCCAGG-1,TTGTTTCATTAGTCTA-1,TTGTTTCCATACAACT-1,TTGTTTGTGTAAATTC-1
0,859.095777,1217.862779,1006.987845,1252.925314,1154.154857,1171.601703,1084.630087,1257.177050,1272.521066,1233.065320,...,1028.060065,1212.526775,1091.689457,1041.828809,505.079169,1046.241228,1121.303611,821.190539,1121.217927,1060.264129
1,861.441265,1221.187463,1009.735907,1256.374956,1157.316257,1174.803261,1087.604531,1260.619862,1276.004709,1236.448523,...,1030.871239,1215.844830,1094.670311,1044.676889,506.454260,1049.103906,1124.365936,823.434253,1124.276423,1063.175349
2,866.985896,1229.048553,1016.237533,1264.439238,1164.757029,1182.362279,1094.594030,1268.724135,1284.212443,1244.393407,...,1037.503578,1223.664692,1101.717724,1051.399420,509.716190,1055.850505,1131.602851,828.736181,1131.514627,1070.008601
3,862.340020,1222.463531,1010.791343,1257.674328,1158.519216,1176.028594,1088.734374,1261.931034,1277.333656,1237.732284,...,1031.945995,1217.111930,1095.814328,1045.767565,506.984662,1050.196359,1125.541169,824.294494,1125.451821,1064.279339
4,857.248978,1215.241910,1004.822031,1250.221657,1151.671270,1169.079730,1082.291562,1254.472115,1269.780306,1230.407057,...,1025.848108,1209.914804,1089.338956,1039.584264,503.995301,1043.988922,1118.888124,819.423052,1118.807765,1057.973030
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,861.049434,1220.632736,1009.278164,1255.801454,1156.788060,1174.271126,1087.109695,1260.043358,1275.425036,1235.885218,...,1030.401730,1215.292500,1094.174500,1044.204476,506.222390,1048.626409,1123.857785,823.061526,1123.763903,1062.696255
996,856.342582,1213.960303,1003.761243,1248.922335,1150.459351,1167.849921,1081.160338,1253.151803,1268.449396,1229.121329,...,1024.766982,1208.646296,1088.192649,1038.494236,503.457429,1042.891006,1117.712535,818.560808,1117.622765,1056.878392
997,856.584323,1214.302674,1004.044652,1249.266548,1150.780797,1168.175737,1081.458634,1253.505303,1268.802045,1229.462573,...,1025.054825,1208.983026,1088.496577,1038.783790,503.602548,1043.183228,1118.024507,818.788849,1117.941457,1057.163349
998,862.573839,1222.791046,1011.062669,1258.015672,1158.833568,1176.345750,1089.027859,1262.271620,1277.677293,1238.066372,...,1032.223237,1217.438916,1096.107957,1046.047651,507.120694,1050.479986,1125.842926,824.515156,1125.753522,1064.566185
999,864.891074,1226.074326,1013.776657,1261.406934,1161.950062,1179.505889,1091.959073,1265.668167,1281.113757,1241.399710,...,1034.997590,1220.713666,1099.051623,1048.857822,508.481986,1053.304412,1128.865866,826.728847,1128.776257,1067.431782

In [47]:
df_res672.T

,AAACAAGTATCTCCCA-1,AAACACCAATAACTGC-1,AAACAGAGCGACTCCT-1,AAACAGCTTTCAGAAG-1,AAACAGGGTCTATATT-1,AAACATTTCCCGGATT-1,AAACCACTACACAGAT-1,AAACCCGAACGAAATC-1,AAACCGGAAATGTTAA-1,AAACCGGGTAGGTACC-1,...,TTGTGTATGCCACCAA-1,TTGTGTTTCCCGAAAG-1,TTGTTAGCAAATTCGA-1,TTGTTCAGTGTGCTAC-1,TTGTTCTAGATACGCT-1,TTGTTGTGTGTCAAGA-1,TTGTTTCACATCCAGG-1,TTGTTTCATTAGTCTA-1,TTGTTTCCATACAACT-1,TTGTTTGTGTAAATTC-1
0,1229.357971,1275.827736,1173.262468,1159.732438,1347.536835,1177.873464,1192.026579,1313.450272,1293.403301,1229.628132,...,952.895996,932.703666,1231.511597,1198.560388,901.656211,1124.996200,839.577035,1003.222325,1264.648657,1294.504827
1,1215.126101,1261.074460,1159.711873,1146.328423,1331.962722,1164.245523,1178.233176,1298.268485,1278.445939,1215.402795,...,941.894205,921.908579,1217.272576,1184.705910,891.246140,1111.976772,829.889944,991.615434,1250.026437,1279.548654
2,1238.620480,1285.444808,1182.110836,1168.476356,1357.696726,1186.750612,1201.009636,1323.352955,1303.152736,1238.895123,...,960.083174,939.731782,1240.795446,1207.596198,908.457368,1133.473374,845.911242,1010.782274,1274.182217,1304.265791
3,1242.752526,1289.728636,1186.044482,1172.367390,1362.218043,1190.705993,1205.014706,1327.760351,1307.494788,1243.024844,...,963.276189,942.865330,1244.928420,1211.617638,911.478857,1137.252523,848.722583,1014.151014,1278.428005,1308.607312
4,1243.444011,1290.434826,1186.683703,1173.005826,1362.959124,1191.363705,1205.680862,1328.483600,1308.211658,1243.710271,...,963.792926,943.388901,1245.609882,1212.278183,911.966723,1137.882577,849.174102,1014.711676,1279.126903,1309.315829
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1245.281957,1292.343860,1188.440279,1174.741279,1364.975579,1193.125274,1207.463154,1330.448943,1310.146848,1245.549550,...,965.219503,944.783351,1247.452569,1214.071871,913.316878,1139.564627,850.430808,1016.212244,1281.019003,1311.253578
996,1238.077784,1284.866105,1181.561384,1167.942906,1357.076117,1186.220729,1200.477209,1322.749624,1302.565536,1238.342342,...,959.633001,939.317045,1240.233399,1207.045509,908.030492,1132.970498,845.508196,1010.331303,1273.606826,1303.664475
997,1234.724930,1281.390413,1178.370721,1164.786187,1353.408574,1183.012159,1197.227803,1319.174168,1299.042620,1234.991842,...,957.042460,936.774040,1236.880201,1203.783262,905.579387,1129.904855,843.227697,1007.598841,1270.162268,1300.142580
998,1234.471166,1281.127484,1178.130232,1164.547662,1353.132143,1182.770286,1196.982274,1318.904462,1298.776735,1234.739098,...,956.847628,936.582407,1236.627428,1203.537597,905.394964,1129.673833,843.056376,1007.392962,1269.901514,1299.877661
999,1229.823827,1276.304896,1173.693694,1160.162663,1348.036468,1178.315377,1192.475884,1313.938288,1293.886207,1230.089464,...,953.244196,933.055107,1231.970096,1199.004948,901.984995,1125.419327,839.880625,1003.597928,1265.121237,1294.982521

In [48]:
df_res673.T

,AAACAAGTATCTCCCA-1,AAACAATCTACTAGCA-1,AAACACCAATAACTGC-1,AAACAGAGCGACTCCT-1,AAACAGCTTTCAGAAG-1,AAACAGGGTCTATATT-1,AAACAGTGTTCCTGGG-1,AAACATTTCCCGGATT-1,AAACCCGAACGAAATC-1,AAACCGGGTAGGTACC-1,...,TTGTGTATGCCACCAA-1,TTGTGTTTCCCGAAAG-1,TTGTTAGCAAATTCGA-1,TTGTTCAGTGTGCTAC-1,TTGTTGTGTGTCAAGA-1,TTGTTTCACATCCAGG-1,TTGTTTCATTAGTCTA-1,TTGTTTCCATACAACT-1,TTGTTTGTATTACACG-1,TTGTTTGTGTAAATTC-1
0,1302.476740,995.567327,1227.763278,1236.889512,1204.291079,1238.849751,1089.618437,1298.553460,1366.096365,915.117156,...,866.122385,1025.044247,1206.020059,1273.446986,1197.675696,1249.992099,1118.985710,1106.651527,1108.654638,1218.377372
1,1305.942491,998.231014,1231.043194,1240.183773,1207.492285,1242.136562,1092.528843,1302.008661,1369.728919,917.545439,...,868.436897,1027.781870,1209.224738,1276.826232,1200.856066,1253.331722,1121.967003,1109.597934,1111.602618,1221.617583
2,1312.185041,1003.017273,1236.943013,1246.110465,1213.257308,1248.045209,1097.752935,1308.229982,1376.264804,921.920557,...,872.599695,1032.715023,1214.991127,1282.913134,1206.585340,1259.327513,1127.326190,1114.904606,1116.919072,1227.453520
3,1301.921395,995.144191,1227.237270,1236.361455,1203.778364,1238.326381,1089.154647,1297.998498,1365.513466,914.723703,...,865.752412,1024.606045,1205.505472,1272.903917,1197.167230,1249.457410,1118.510801,1106.179331,1108.179641,1217.857371
4,1307.536589,999.441641,1232.541810,1241.698583,1208.969724,1243.660547,1093.860135,1303.601013,1371.405600,918.675934,...,869.492733,1029.029640,1210.705748,1278.394344,1202.324450,1254.858360,1123.334795,1110.953637,1112.962405,1223.113897
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1315.614976,1005.626820,1240.162748,1249.370192,1216.434943,1251.332024,1100.620655,1311.652972,1379.873064,924.343510,...,874.871695,1035.398293,1218.180711,1286.282644,1209.750086,1262.614463,1130.273241,1117.816787,1119.836832,1230.667367
996,1305.360998,997.794538,1230.500783,1239.629391,1206.951888,1241.573260,1092.046716,1301.426267,1369.114294,917.129602,...,868.058125,1027.331584,1208.680092,1276.248577,1200.317945,1252.778716,1121.468318,1109.102467,1111.108188,1221.071600
997,1316.032565,1005.946751,1240.554527,1249.763626,1216.818680,1251.723914,1100.966267,1312.065959,1380.305768,924.630895,...,875.148164,1035.729984,1218.562062,1286.684547,1210.133227,1263.010717,1130.631046,1118.168794,1120.191531,1231.052491
998,1304.545635,997.142343,1229.704553,1238.848430,1206.201950,1240.817274,1091.342214,1300.612177,1368.259691,916.567558,...,867.494502,1026.676551,1207.932257,1275.465741,1199.580705,1251.965976,1120.761389,1108.409597,1110.416091,1220.309042
999,1312.087586,1002.921965,1236.833393,1246.019642,1213.178159,1247.988396,1097.668833,1308.138315,1376.180230,921.873317,...,872.521883,1032.614092,1214.921917,1282.844755,1206.509901,1259.229260,1127.244648,1114.821412,1116.838100,1227.372877

In [49]:
embed_507 = df_res507.T
embed_507

,AAACAACGAATAGTTC-1,AAACAAGTATCTCCCA-1,AAACAATCTACTAGCA-1,AAACACCAATAACTGC-1,AAACAGCTTTCAGAAG-1,AAACAGGGTCTATATT-1,AAACAGTGTTCCTGGG-1,AAACATTTCCCGGATT-1,AAACCACTACACAGAT-1,AAACCCGAACGAAATC-1,...,TTGTGTATGCCACCAA-1,TTGTGTTTCCCGAAAG-1,TTGTTAGCAAATTCGA-1,TTGTTCAGTGTGCTAC-1,TTGTTCTAGATACGCT-1,TTGTTGTGTGTCAAGA-1,TTGTTTCACATCCAGG-1,TTGTTTCATTAGTCTA-1,TTGTTTCCATACAACT-1,TTGTTTGTGTAAATTC-1
0,859.095777,1217.862779,1006.987845,1252.925314,1154.154857,1171.601703,1084.630087,1257.177050,1272.521066,1233.065320,...,1028.060065,1212.526775,1091.689457,1041.828809,505.079169,1046.241228,1121.303611,821.190539,1121.217927,1060.264129
1,861.441265,1221.187463,1009.735907,1256.374956,1157.316257,1174.803261,1087.604531,1260.619862,1276.004709,1236.448523,...,1030.871239,1215.844830,1094.670311,1044.676889,506.454260,1049.103906,1124.365936,823.434253,1124.276423,1063.175349
2,866.985896,1229.048553,1016.237533,1264.439238,1164.757029,1182.362279,1094.594030,1268.724135,1284.212443,1244.393407,...,1037.503578,1223.664692,1101.717724,1051.399420,509.716190,1055.850505,1131.602851,828.736181,1131.514627,1070.008601
3,862.340020,1222.463531,1010.791343,1257.674328,1158.519216,1176.028594,1088.734374,1261.931034,1277.333656,1237.732284,...,1031.945995,1217.111930,1095.814328,1045.767565,506.984662,1050.196359,1125.541169,824.294494,1125.451821,1064.279339
4,857.248978,1215.241910,1004.822031,1250.221657,1151.671270,1169.079730,1082.291562,1254.472115,1269.780306,1230.407057,...,1025.848108,1209.914804,1089.338956,1039.584264,503.995301,1043.988922,1118.888124,819.423052,1118.807765,1057.973030
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,861.049434,1220.632736,1009.278164,1255.801454,1156.788060,1174.271126,1087.109695,1260.043358,1275.425036,1235.885218,...,1030.401730,1215.292500,1094.174500,1044.204476,506.222390,1048.626409,1123.857785,823.061526,1123.763903,1062.696255
996,856.342582,1213.960303,1003.761243,1248.922335,1150.459351,1167.849921,1081.160338,1253.151803,1268.449396,1229.121329,...,1024.766982,1208.646296,1088.192649,1038.494236,503.457429,1042.891006,1117.712535,818.560808,1117.622765,1056.878392
997,856.584323,1214.302674,1004.044652,1249.266548,1150.780797,1168.175737,1081.458634,1253.505303,1268.802045,1229.462573,...,1025.054825,1208.983026,1088.496577,1038.783790,503.602548,1043.183228,1118.024507,818.788849,1117.941457,1057.163349
998,862.573839,1222.791046,1011.062669,1258.015672,1158.833568,1176.345750,1089.027859,1262.271620,1277.677293,1238.066372,...,1032.223237,1217.438916,1096.107957,1046.047651,507.120694,1050.479986,1125.842926,824.515156,1125.753522,1064.566185
999,864.891074,1226.074326,1013.776657,1261.406934,1161.950062,1179.505889,1091.959073,1265.668167,1281.113757,1241.399710,...,1034.997590,1220.713666,1099.051623,1048.857822,508.481986,1053.304412,1128.865866,826.728847,1128.776257,1067.431782

In [50]:
embed_672 = df_res672.T
embed_672

,AAACAAGTATCTCCCA-1,AAACACCAATAACTGC-1,AAACAGAGCGACTCCT-1,AAACAGCTTTCAGAAG-1,AAACAGGGTCTATATT-1,AAACATTTCCCGGATT-1,AAACCACTACACAGAT-1,AAACCCGAACGAAATC-1,AAACCGGAAATGTTAA-1,AAACCGGGTAGGTACC-1,...,TTGTGTATGCCACCAA-1,TTGTGTTTCCCGAAAG-1,TTGTTAGCAAATTCGA-1,TTGTTCAGTGTGCTAC-1,TTGTTCTAGATACGCT-1,TTGTTGTGTGTCAAGA-1,TTGTTTCACATCCAGG-1,TTGTTTCATTAGTCTA-1,TTGTTTCCATACAACT-1,TTGTTTGTGTAAATTC-1
0,1229.357971,1275.827736,1173.262468,1159.732438,1347.536835,1177.873464,1192.026579,1313.450272,1293.403301,1229.628132,...,952.895996,932.703666,1231.511597,1198.560388,901.656211,1124.996200,839.577035,1003.222325,1264.648657,1294.504827
1,1215.126101,1261.074460,1159.711873,1146.328423,1331.962722,1164.245523,1178.233176,1298.268485,1278.445939,1215.402795,...,941.894205,921.908579,1217.272576,1184.705910,891.246140,1111.976772,829.889944,991.615434,1250.026437,1279.548654
2,1238.620480,1285.444808,1182.110836,1168.476356,1357.696726,1186.750612,1201.009636,1323.352955,1303.152736,1238.895123,...,960.083174,939.731782,1240.795446,1207.596198,908.457368,1133.473374,845.911242,1010.782274,1274.182217,1304.265791
3,1242.752526,1289.728636,1186.044482,1172.367390,1362.218043,1190.705993,1205.014706,1327.760351,1307.494788,1243.024844,...,963.276189,942.865330,1244.928420,1211.617638,911.478857,1137.252523,848.722583,1014.151014,1278.428005,1308.607312
4,1243.444011,1290.434826,1186.683703,1173.005826,1362.959124,1191.363705,1205.680862,1328.483600,1308.211658,1243.710271,...,963.792926,943.388901,1245.609882,1212.278183,911.966723,1137.882577,849.174102,1014.711676,1279.126903,1309.315829
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1245.281957,1292.343860,1188.440279,1174.741279,1364.975579,1193.125274,1207.463154,1330.448943,1310.146848,1245.549550,...,965.219503,944.783351,1247.452569,1214.071871,913.316878,1139.564627,850.430808,1016.212244,1281.019003,1311.253578
996,1238.077784,1284.866105,1181.561384,1167.942906,1357.076117,1186.220729,1200.477209,1322.749624,1302.565536,1238.342342,...,959.633001,939.317045,1240.233399,1207.045509,908.030492,1132.970498,845.508196,1010.331303,1273.606826,1303.664475
997,1234.724930,1281.390413,1178.370721,1164.786187,1353.408574,1183.012159,1197.227803,1319.174168,1299.042620,1234.991842,...,957.042460,936.774040,1236.880201,1203.783262,905.579387,1129.904855,843.227697,1007.598841,1270.162268,1300.142580
998,1234.471166,1281.127484,1178.130232,1164.547662,1353.132143,1182.770286,1196.982274,1318.904462,1298.776735,1234.739098,...,956.847628,936.582407,1236.627428,1203.537597,905.394964,1129.673833,843.056376,1007.392962,1269.901514,1299.877661
999,1229.823827,1276.304896,1173.693694,1160.162663,1348.036468,1178.315377,1192.475884,1313.938288,1293.886207,1230.089464,...,953.244196,933.055107,1231.970096,1199.004948,901.984995,1125.419327,839.880625,1003.597928,1265.121237,1294.982521

In [51]:
embed_673 = df_res673.T
embed_673

,AAACAAGTATCTCCCA-1,AAACAATCTACTAGCA-1,AAACACCAATAACTGC-1,AAACAGAGCGACTCCT-1,AAACAGCTTTCAGAAG-1,AAACAGGGTCTATATT-1,AAACAGTGTTCCTGGG-1,AAACATTTCCCGGATT-1,AAACCCGAACGAAATC-1,AAACCGGGTAGGTACC-1,...,TTGTGTATGCCACCAA-1,TTGTGTTTCCCGAAAG-1,TTGTTAGCAAATTCGA-1,TTGTTCAGTGTGCTAC-1,TTGTTGTGTGTCAAGA-1,TTGTTTCACATCCAGG-1,TTGTTTCATTAGTCTA-1,TTGTTTCCATACAACT-1,TTGTTTGTATTACACG-1,TTGTTTGTGTAAATTC-1
0,1302.476740,995.567327,1227.763278,1236.889512,1204.291079,1238.849751,1089.618437,1298.553460,1366.096365,915.117156,...,866.122385,1025.044247,1206.020059,1273.446986,1197.675696,1249.992099,1118.985710,1106.651527,1108.654638,1218.377372
1,1305.942491,998.231014,1231.043194,1240.183773,1207.492285,1242.136562,1092.528843,1302.008661,1369.728919,917.545439,...,868.436897,1027.781870,1209.224738,1276.826232,1200.856066,1253.331722,1121.967003,1109.597934,1111.602618,1221.617583
2,1312.185041,1003.017273,1236.943013,1246.110465,1213.257308,1248.045209,1097.752935,1308.229982,1376.264804,921.920557,...,872.599695,1032.715023,1214.991127,1282.913134,1206.585340,1259.327513,1127.326190,1114.904606,1116.919072,1227.453520
3,1301.921395,995.144191,1227.237270,1236.361455,1203.778364,1238.326381,1089.154647,1297.998498,1365.513466,914.723703,...,865.752412,1024.606045,1205.505472,1272.903917,1197.167230,1249.457410,1118.510801,1106.179331,1108.179641,1217.857371
4,1307.536589,999.441641,1232.541810,1241.698583,1208.969724,1243.660547,1093.860135,1303.601013,1371.405600,918.675934,...,869.492733,1029.029640,1210.705748,1278.394344,1202.324450,1254.858360,1123.334795,1110.953637,1112.962405,1223.113897
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1315.614976,1005.626820,1240.162748,1249.370192,1216.434943,1251.332024,1100.620655,1311.652972,1379.873064,924.343510,...,874.871695,1035.398293,1218.180711,1286.282644,1209.750086,1262.614463,1130.273241,1117.816787,1119.836832,1230.667367
996,1305.360998,997.794538,1230.500783,1239.629391,1206.951888,1241.573260,1092.046716,1301.426267,1369.114294,917.129602,...,868.058125,1027.331584,1208.680092,1276.248577,1200.317945,1252.778716,1121.468318,1109.102467,1111.108188,1221.071600
997,1316.032565,1005.946751,1240.554527,1249.763626,1216.818680,1251.723914,1100.966267,1312.065959,1380.305768,924.630895,...,875.148164,1035.729984,1218.562062,1286.684547,1210.133227,1263.010717,1130.631046,1118.168794,1120.191531,1231.052491
998,1304.545635,997.142343,1229.704553,1238.848430,1206.201950,1240.817274,1091.342214,1300.612177,1368.259691,916.567558,...,867.494502,1026.676551,1207.932257,1275.465741,1199.580705,1251.965976,1120.761389,1108.409597,1110.416091,1220.309042
999,1312.087586,1002.921965,1236.833393,1246.019642,1213.178159,1247.988396,1097.668833,1308.138315,1376.180230,921.873317,...,872.521883,1032.614092,1214.921917,1282.844755,1206.509901,1259.229260,1127.244648,1114.821412,1116.838100,1227.372877

In [52]:
embed_507_672 = pd.concat([embed_507,embed_672],axis=1)
embed_507_672

,AAACAACGAATAGTTC-1,AAACAAGTATCTCCCA-1,AAACAATCTACTAGCA-1,AAACACCAATAACTGC-1,AAACAGCTTTCAGAAG-1,AAACAGGGTCTATATT-1,AAACAGTGTTCCTGGG-1,AAACATTTCCCGGATT-1,AAACCACTACACAGAT-1,AAACCCGAACGAAATC-1,...,TTGTGTATGCCACCAA-1,TTGTGTTTCCCGAAAG-1,TTGTTAGCAAATTCGA-1,TTGTTCAGTGTGCTAC-1,TTGTTCTAGATACGCT-1,TTGTTGTGTGTCAAGA-1,TTGTTTCACATCCAGG-1,TTGTTTCATTAGTCTA-1,TTGTTTCCATACAACT-1,TTGTTTGTGTAAATTC-1
0,859.095777,1217.862779,1006.987845,1252.925314,1154.154857,1171.601703,1084.630087,1257.177050,1272.521066,1233.065320,...,952.895996,932.703666,1231.511597,1198.560388,901.656211,1124.996200,839.577035,1003.222325,1264.648657,1294.504827
1,861.441265,1221.187463,1009.735907,1256.374956,1157.316257,1174.803261,1087.604531,1260.619862,1276.004709,1236.448523,...,941.894205,921.908579,1217.272576,1184.705910,891.246140,1111.976772,829.889944,991.615434,1250.026437,1279.548654
2,866.985896,1229.048553,1016.237533,1264.439238,1164.757029,1182.362279,1094.594030,1268.724135,1284.212443,1244.393407,...,960.083174,939.731782,1240.795446,1207.596198,908.457368,1133.473374,845.911242,1010.782274,1274.182217,1304.265791
3,862.340020,1222.463531,1010.791343,1257.674328,1158.519216,1176.028594,1088.734374,1261.931034,1277.333656,1237.732284,...,963.276189,942.865330,1244.928420,1211.617638,911.478857,1137.252523,848.722583,1014.151014,1278.428005,1308.607312
4,857.248978,1215.241910,1004.822031,1250.221657,1151.671270,1169.079730,1082.291562,1254.472115,1269.780306,1230.407057,...,963.792926,943.388901,1245.609882,1212.278183,911.966723,1137.882577,849.174102,1014.711676,1279.126903,1309.315829
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,861.049434,1220.632736,1009.278164,1255.801454,1156.788060,1174.271126,1087.109695,1260.043358,1275.425036,1235.885218,...,965.219503,944.783351,1247.452569,1214.071871,913.316878,1139.564627,850.430808,1016.212244,1281.019003,1311.253578
996,856.342582,1213.960303,1003.761243,1248.922335,1150.459351,1167.849921,1081.160338,1253.151803,1268.449396,1229.121329,...,959.633001,939.317045,1240.233399,1207.045509,908.030492,1132.970498,845.508196,1010.331303,1273.606826,1303.664475
997,856.584323,1214.302674,1004.044652,1249.266548,1150.780797,1168.175737,1081.458634,1253.505303,1268.802045,1229.462573,...,957.042460,936.774040,1236.880201,1203.783262,905.579387,1129.904855,843.227697,1007.598841,1270.162268,1300.142580
998,862.573839,1222.791046,1011.062669,1258.015672,1158.833568,1176.345750,1089.027859,1262.271620,1277.677293,1238.066372,...,956.847628,936.582407,1236.627428,1203.537597,905.394964,1129.673833,843.056376,1007.392962,1269.901514,1299.877661
999,864.891074,1226.074326,1013.776657,1261.406934,1161.950062,1179.505889,1091.959073,1265.668167,1281.113757,1241.399710,...,953.244196,933.055107,1231.970096,1199.004948,901.984995,1125.419327,839.880625,1003.597928,1265.121237,1294.982521

In [53]:
embed_all = pd.concat([embed_507_672,embed_673],axis=1)
embed_all

,AAACAACGAATAGTTC-1,AAACAAGTATCTCCCA-1,AAACAATCTACTAGCA-1,AAACACCAATAACTGC-1,AAACAGCTTTCAGAAG-1,AAACAGGGTCTATATT-1,AAACAGTGTTCCTGGG-1,AAACATTTCCCGGATT-1,AAACCACTACACAGAT-1,AAACCCGAACGAAATC-1,...,TTGTGTATGCCACCAA-1,TTGTGTTTCCCGAAAG-1,TTGTTAGCAAATTCGA-1,TTGTTCAGTGTGCTAC-1,TTGTTGTGTGTCAAGA-1,TTGTTTCACATCCAGG-1,TTGTTTCATTAGTCTA-1,TTGTTTCCATACAACT-1,TTGTTTGTATTACACG-1,TTGTTTGTGTAAATTC-1
0,859.095777,1217.862779,1006.987845,1252.925314,1154.154857,1171.601703,1084.630087,1257.177050,1272.521066,1233.065320,...,866.122385,1025.044247,1206.020059,1273.446986,1197.675696,1249.992099,1118.985710,1106.651527,1108.654638,1218.377372
1,861.441265,1221.187463,1009.735907,1256.374956,1157.316257,1174.803261,1087.604531,1260.619862,1276.004709,1236.448523,...,868.436897,1027.781870,1209.224738,1276.826232,1200.856066,1253.331722,1121.967003,1109.597934,1111.602618,1221.617583
2,866.985896,1229.048553,1016.237533,1264.439238,1164.757029,1182.362279,1094.594030,1268.724135,1284.212443,1244.393407,...,872.599695,1032.715023,1214.991127,1282.913134,1206.585340,1259.327513,1127.326190,1114.904606,1116.919072,1227.453520
3,862.340020,1222.463531,1010.791343,1257.674328,1158.519216,1176.028594,1088.734374,1261.931034,1277.333656,1237.732284,...,865.752412,1024.606045,1205.505472,1272.903917,1197.167230,1249.457410,1118.510801,1106.179331,1108.179641,1217.857371
4,857.248978,1215.241910,1004.822031,1250.221657,1151.671270,1169.079730,1082.291562,1254.472115,1269.780306,1230.407057,...,869.492733,1029.029640,1210.705748,1278.394344,1202.324450,1254.858360,1123.334795,1110.953637,1112.962405,1223.113897
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,861.049434,1220.632736,1009.278164,1255.801454,1156.788060,1174.271126,1087.109695,1260.043358,1275.425036,1235.885218,...,874.871695,1035.398293,1218.180711,1286.282644,1209.750086,1262.614463,1130.273241,1117.816787,1119.836832,1230.667367
996,856.342582,1213.960303,1003.761243,1248.922335,1150.459351,1167.849921,1081.160338,1253.151803,1268.449396,1229.121329,...,868.058125,1027.331584,1208.680092,1276.248577,1200.317945,1252.778716,1121.468318,1109.102467,1111.108188,1221.071600
997,856.584323,1214.302674,1004.044652,1249.266548,1150.780797,1168.175737,1081.458634,1253.505303,1268.802045,1229.462573,...,875.148164,1035.729984,1218.562062,1286.684547,1210.133227,1263.010717,1130.631046,1118.168794,1120.191531,1231.052491
998,862.573839,1222.791046,1011.062669,1258.015672,1158.833568,1176.345750,1089.027859,1262.271620,1277.677293,1238.066372,...,867.494502,1026.676551,1207.932257,1275.465741,1199.580705,1251.965976,1120.761389,1108.409597,1110.416091,1220.309042
999,864.891074,1226.074326,1013.776657,1261.406934,1161.950062,1179.505889,1091.959073,1265.668167,1281.113757,1241.399710,...,872.521883,1032.614092,1214.921917,1282.844755,1206.509901,1259.229260,1127.244648,1114.821412,1116.838100,1227.372877

In [54]:
embed_all.fillna(0,inplace=True)
embed_all

,AAACAACGAATAGTTC-1,AAACAAGTATCTCCCA-1,AAACAATCTACTAGCA-1,AAACACCAATAACTGC-1,AAACAGCTTTCAGAAG-1,AAACAGGGTCTATATT-1,AAACAGTGTTCCTGGG-1,AAACATTTCCCGGATT-1,AAACCACTACACAGAT-1,AAACCCGAACGAAATC-1,...,TTGTGTATGCCACCAA-1,TTGTGTTTCCCGAAAG-1,TTGTTAGCAAATTCGA-1,TTGTTCAGTGTGCTAC-1,TTGTTGTGTGTCAAGA-1,TTGTTTCACATCCAGG-1,TTGTTTCATTAGTCTA-1,TTGTTTCCATACAACT-1,TTGTTTGTATTACACG-1,TTGTTTGTGTAAATTC-1
0,859.095777,1217.862779,1006.987845,1252.925314,1154.154857,1171.601703,1084.630087,1257.177050,1272.521066,1233.065320,...,866.122385,1025.044247,1206.020059,1273.446986,1197.675696,1249.992099,1118.985710,1106.651527,1108.654638,1218.377372
1,861.441265,1221.187463,1009.735907,1256.374956,1157.316257,1174.803261,1087.604531,1260.619862,1276.004709,1236.448523,...,868.436897,1027.781870,1209.224738,1276.826232,1200.856066,1253.331722,1121.967003,1109.597934,1111.602618,1221.617583
2,866.985896,1229.048553,1016.237533,1264.439238,1164.757029,1182.362279,1094.594030,1268.724135,1284.212443,1244.393407,...,872.599695,1032.715023,1214.991127,1282.913134,1206.585340,1259.327513,1127.326190,1114.904606,1116.919072,1227.453520
3,862.340020,1222.463531,1010.791343,1257.674328,1158.519216,1176.028594,1088.734374,1261.931034,1277.333656,1237.732284,...,865.752412,1024.606045,1205.505472,1272.903917,1197.167230,1249.457410,1118.510801,1106.179331,1108.179641,1217.857371
4,857.248978,1215.241910,1004.822031,1250.221657,1151.671270,1169.079730,1082.291562,1254.472115,1269.780306,1230.407057,...,869.492733,1029.029640,1210.705748,1278.394344,1202.324450,1254.858360,1123.334795,1110.953637,1112.962405,1223.113897
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,861.049434,1220.632736,1009.278164,1255.801454,1156.788060,1174.271126,1087.109695,1260.043358,1275.425036,1235.885218,...,874.871695,1035.398293,1218.180711,1286.282644,1209.750086,1262.614463,1130.273241,1117.816787,1119.836832,1230.667367
996,856.342582,1213.960303,1003.761243,1248.922335,1150.459351,1167.849921,1081.160338,1253.151803,1268.449396,1229.121329,...,868.058125,1027.331584,1208.680092,1276.248577,1200.317945,1252.778716,1121.468318,1109.102467,1111.108188,1221.071600
997,856.584323,1214.302674,1004.044652,1249.266548,1150.780797,1168.175737,1081.458634,1253.505303,1268.802045,1229.462573,...,875.148164,1035.729984,1218.562062,1286.684547,1210.133227,1263.010717,1130.631046,1118.168794,1120.191531,1231.052491
998,862.573839,1222.791046,1011.062669,1258.015672,1158.833568,1176.345750,1089.027859,1262.271620,1277.677293,1238.066372,...,867.494502,1026.676551,1207.932257,1275.465741,1199.580705,1251.965976,1120.761389,1108.409597,1110.416091,1220.309042
999,864.891074,1226.074326,1013.776657,1261.406934,1161.950062,1179.505889,1091.959073,1265.668167,1281.113757,1241.399710,...,872.521883,1032.614092,1214.921917,1282.844755,1206.509901,1259.229260,1127.244648,1114.821412,1116.838100,1227.372877

In [25]:
# embed_507_672 = pd.concat([embed_507,embed_672],axis=1)
# embed_all = pd.concat([embed_507_672,embed_673],axis=1)
# embed_all

In [55]:
# embed_all.to_csv('dataset/datapoints/embed_all.csv',index = False)

# Save DataFrame to CSV with progress bar
chunks = np.array_split(embed_all.index, 1000) # split into 1000 chunks

for chunck, subset in enumerate(tqdm(chunks)):
    if chunck == 0: # first row
        embed_all.loc[subset].to_csv('dataset/datapoints/embed_all_com4_multi_unfil.csv', mode='w', index=True)
    else:
        embed_all.loc[subset].to_csv('dataset/datapoints/embed_all_com4_multi_unfil.csv', header=None, mode='a', index=True)
# embed_all.to_csv('dataset/datapoints/embed_all_com3.csv',index = True, chunksize=1000)

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:14<00:00, 68.26it/s]

In [56]:
print('saving...')
embed_all.to_pickle('dataset/datapoints/embed_all_com4_multi_unfil.pkl')
print('done')

saving...
done

In [47]:
import sys
a = sys.getsizeof(df_spat507)/(1024 ** 2)
b = sys.getsizeof(df_151507)/(1024 ** 2)
c = sys.getsizeof(df_spat672)/(1024 ** 2)
d = sys.getsizeof(df_151672)/(1024 ** 2)
e = sys.getsizeof(df_spat673)/(1024 ** 2)
f = sys.getsizeof(df_151673)/(1024 ** 2)
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

print('total: ',a+b+c+d+e+f)
print(sys.getsizeof(embed_all)/(1024 ** 2))

1083.789011001587
1083.6290893554688
1029.7994632720947
1029.6395416259766
933.5906009674072
933.4306793212891
total:  6093.878385543823
6086.362642288208

In [42]:
import sys
a = sys.getsizeof(df_spat507)/(1024 ** 2)
b = sys.getsizeof(df_151507)/(1024 ** 2)
c = sys.getsizeof(df_spat672)/(1024 ** 2)
d = sys.getsizeof(df_151672)/(1024 ** 2)
e = sys.getsizeof(df_spat673)/(1024 ** 2)
f = sys.getsizeof(df_151673)/(1024 ** 2)
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

print('total: ',a+b+c+d+e+f)
print(sys.getsizeof(embed_all)/(1024 ** 2))

1083.6290893554688
1084.6369400024414
1029.6395416259766
1029.6395416259766
933.4306793212891
933.4306793212891
total:  6094.406471252441
3043.101387023926

In [23]:
# embed_507.to_csv('datapoints/embedded_507.csv', index=False)
pyreadr.write_rds('datapoints/embed_507.rds', embed_507, compress='gzip')

In [24]:
pyreadr.write_rds('datapoints/embed_672.rds', embed_672, compress='gzip')

In [25]:
pyreadr.write_rds('datapoints/embed_673.rds', embed_673, compress='gzip')

In [13]:
# filters gene with 0 value throughout assay matrix
summ = df_151507.sum(axis=1)
filtered_151507 = df_151507.loc[summ>0]
summ = df_151672.sum(axis=1)
filtered_151672 = df_151672.loc[summ>0]
summ = df_151673.sum(axis=1)
filtered_151673 = df_151673.loc[summ>0]
summ = combined_all.sum(axis=1)
filtered_all = combined_all.loc[summ>0]

# this results in a non-uniform rows, should concate first before filters

In [14]:
# selected gene after filtering non-zero across all samples
df = pd.DataFrame(filtered_all.index.tolist())
selected_gene = df[0].tolist()

In [17]:
len(selected_gene)

23465

In [15]:
df_151673.loc[selected_gene]

,AAACAAGTATCTCCCA-1,AAACAATCTACTAGCA-1,AAACACCAATAACTGC-1,AAACAGAGCGACTCCT-1,AAACAGCTTTCAGAAG-1,AAACAGGGTCTATATT-1,AAACAGTGTTCCTGGG-1,AAACATTTCCCGGATT-1,AAACCCGAACGAAATC-1,AAACCGGGTAGGTACC-1,...,TTGTGTATGCCACCAA-1,TTGTGTTTCCCGAAAG-1,TTGTTAGCAAATTCGA-1,TTGTTCAGTGTGCTAC-1,TTGTTGTGTGTCAAGA-1,TTGTTTCACATCCAGG-1,TTGTTTCATTAGTCTA-1,TTGTTTCCATACAACT-1,TTGTTTGTATTACACG-1,TTGTTTGTGTAAATTC-1
rownames,,,,,,,,,,,,,,,,,,,,,
ENSG00000243485,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ENSG00000238009,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ENSG00000229905,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ENSG00000237491,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ENSG00000177757,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000278817,0.0,0.0,0.0,0.0,0.804885,0.0,0.0,0.481892,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ENSG00000277196,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.328571,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ENSG00000278384,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ENSG00000271254,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ENSG00000268674,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
df['coord_list'] = pd.Series(dtype=str)
df['coord_count'] = pd.Series(dtype=int)

In [20]:
df_507 = df.copy()
df_673 = df.copy()
df_672 = df.copy()

In [21]:
df

                     0 coord_list  coord_count
0      ENSG00000243485        NaN          NaN
1      ENSG00000238009        NaN          NaN
2      ENSG00000229905        NaN          NaN
3      ENSG00000237491        NaN          NaN
4      ENSG00000177757        NaN          NaN
...                ...        ...          ...
23460  ENSG00000278817        NaN          NaN
23461  ENSG00000277196        NaN          NaN
23462  ENSG00000278384        NaN          NaN
23463  ENSG00000271254        NaN          NaN
23464  ENSG00000268674        NaN          NaN

[23465 rows x 3 columns]

<h1>Preprocess

In [22]:
# assay into multiple instances

# read each spots coordinates
coord507 = pyreadr.read_r('spatialLIBD/r_lib/coord_151507.rds')
coord672 = pyreadr.read_r('spatialLIBD/r_lib/coord_151672.rds')
coord673 = pyreadr.read_r('spatialLIBD/r_lib/coord_151673.rds')

# coordinates in respect to gene count values

# output should be matrix of gene distribution for each gene

In [23]:
coord507 = coord507[None]
coord672 = coord672[None]
coord673 = coord673[None]

In [24]:
coord507

                    pxl_col_in_fullres  pxl_row_in_fullres
AAACAACGAATAGTTC-1              3276.0              2514.0
AAACAAGTATCTCCCA-1              9178.0              8520.0
AAACAATCTACTAGCA-1              5133.0              2878.0
AAACACCAATAACTGC-1              3462.0              9581.0
AAACAGCTTTCAGAAG-1              2779.0              7663.0
...                                ...                 ...
TTGTTGTGTGTCAAGA-1              7464.0              6239.0
TTGTTTCACATCCAGG-1              5045.0              9466.0
TTGTTTCATTAGTCTA-1              4218.0              9703.0
TTGTTTCCATACAACT-1              4017.0              7906.0
TTGTTTGTGTAAATTC-1              5683.0              3359.0

[4226 rows x 2 columns]

In [530]:
coord672

                    pxl_col_in_fullres  pxl_row_in_fullres
AAACAAGTATCTCCCA-1             10215.0              8703.0
AAACACCAATAACTGC-1              4499.0              9767.0
AAACAGAGCGACTCCT-1              9675.0              4390.0
AAACAGCTTTCAGAAG-1              3816.0              7849.0
AAACAGGGTCTATATT-1              4090.0              8329.0
...                                ...                 ...
TTGTTGTGTGTCAAGA-1              8500.0              6423.0
TTGTTTCACATCCAGG-1              6083.0              9651.0
TTGTTTCATTAGTCTA-1              5256.0              9889.0
TTGTTTCCATACAACT-1              5054.0              8092.0
TTGTTTGTGTAAATTC-1              6717.0              3544.0

[4015 rows x 2 columns]

In [431]:
coord673

                    pxl_col_in_fullres  pxl_row_in_fullres
AAACAAGTATCTCCCA-1              9791.0              8468.0
AAACAATCTACTAGCA-1              5769.0              2807.0
AAACACCAATAACTGC-1              4068.0              9505.0
AAACAGAGCGACTCCT-1              9271.0              4151.0
AAACAGCTTTCAGAAG-1              3393.0              7583.0
...                                ...                 ...
TTGTTTCACATCCAGG-1              5653.0              9396.0
TTGTTTCATTAGTCTA-1              4825.0              9630.0
TTGTTTCCATACAACT-1              4631.0              7831.0
TTGTTTGTATTACACG-1              5571.0             11193.0
TTGTTTGTGTAAATTC-1              6317.0              3291.0

[3639 rows x 2 columns]

<h5> get coordinate list from assay

In [541]:
# get selected gene from individual sample
select_507 = df_151507.loc[selected_gene]
select_507

,AAACAACGAATAGTTC-1,AAACAAGTATCTCCCA-1,AAACAATCTACTAGCA-1,AAACACCAATAACTGC-1,AAACAGCTTTCAGAAG-1,AAACAGGGTCTATATT-1,AAACAGTGTTCCTGGG-1,AAACATTTCCCGGATT-1,AAACCACTACACAGAT-1,AAACCCGAACGAAATC-1,...,TTGTGTATGCCACCAA-1,TTGTGTTTCCCGAAAG-1,TTGTTAGCAAATTCGA-1,TTGTTCAGTGTGCTAC-1,TTGTTCTAGATACGCT-1,TTGTTGTGTGTCAAGA-1,TTGTTTCACATCCAGG-1,TTGTTTCATTAGTCTA-1,TTGTTTCCATACAACT-1,TTGTTTGTGTAAATTC-1
rownames,,,,,,,,,,,,,,,,,,,,,
ENSG00000243485,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ENSG00000238009,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ENSG00000229905,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ENSG00000237491,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ENSG00000177757,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000278817,0.0,0.841739,0.0,0.0,0.0,0.0,1.382027,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ENSG00000277196,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.593077,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ENSG00000278384,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ENSG00000271254,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ENSG00000268674,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [542]:
# fiters rows from assays, get coordinate list and coordinate count
for i in tqdm(range(len(filtered_all))):   
    a = select_507.iloc[i]
    df_507.loc[i, 'coord_list'] = str(a[a>0].index.tolist())
    df_507.loc[i, 'coord_count'] = len(a[a>0].index.tolist())

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 23465/23465 [00:39<00:00, 597.50it/s]

In [543]:
# Number of gene that have non-zero values, from the initial 33538. should be used as the final shape
df

                     0 coord_list  coord_count
0      ENSG00000243485        NaN          NaN
1      ENSG00000238009        NaN          NaN
2      ENSG00000229905        NaN          NaN
3      ENSG00000237491        NaN          NaN
4      ENSG00000177757        NaN          NaN
...                ...        ...          ...
23460  ENSG00000278817        NaN          NaN
23461  ENSG00000277196        NaN          NaN
23462  ENSG00000278384        NaN          NaN
23463  ENSG00000271254        NaN          NaN
23464  ENSG00000268674        NaN          NaN

[23465 rows x 3 columns]

In [544]:
df_672

,0,coord_list,coord_count
0,ENSG00000243485,[],0.0
1,ENSG00000238009,"['ACCCTATAGGACTGAG-1', 'ATCGCCAGTCAACATT-1', '...",13.0
2,ENSG00000229905,['GCTAAACCTGAGGTGA-1'],1.0
3,ENSG00000237491,"['AACCAAGACTTCTCTG-1', 'AACCCTACTGTCAATA-1', '...",84.0
4,ENSG00000177757,[],0.0
...,...,...,...
23460,ENSG00000278817,"['AAACCGGAAATGTTAA-1', 'AAACGACAGTCTTGCC-1', '...",620.0
23461,ENSG00000277196,"['AAATTGGTGAGAAGCA-1', 'AAATTTGCGGGTGTGG-1', '...",65.0
23462,ENSG00000278384,"['CCCAACATACGTCGCG-1', 'TATTAACACCAAAGCA-1']",2.0
23463,ENSG00000271254,"['AATTGAACGCTCTGGT-1', 'AGACCATGGGATACAA-1', '...",7.0
23464,ENSG00000268674,[],0.0

In [545]:
df_507

,0,coord_list,coord_count
0,ENSG00000243485,['TTGCCAAGCAGAACCC-1'],1.0
1,ENSG00000238009,"['CGCAATTAGGGTAATA-1', 'CTGCAAGCACGTTCCG-1', '...",6.0
2,ENSG00000229905,[],0.0
3,ENSG00000237491,"['AAAGACCCAAGTCGCG-1', 'AAAGTAGCATTGCTCA-1', '...",57.0
4,ENSG00000177757,['GGAGGGTCAAGTAAGA-1'],1.0
...,...,...,...
23460,ENSG00000278817,"['AAACAAGTATCTCCCA-1', 'AAACAGTGTTCCTGGG-1', '...",530.0
23461,ENSG00000277196,"['AAACCACTACACAGAT-1', 'AACTGGGTTCGAGCCG-1', '...",44.0
23462,ENSG00000278384,"['AGTCACTCCGCCTCAT-1', 'ATACGGTGAAGATGCA-1']",2.0
23463,ENSG00000271254,"['AGAAGGTTGCCGAATT-1', 'AGACTGTTACCGGGTC-1', '...",6.0
23464,ENSG00000268674,[],0.0

<h3>Filter genes with minimum points of coordinates (currently 250)

In [546]:
# filter genes with minimum points of coordinates
df_507_min = df_507.loc[:][df_507.loc[:]['coord_count']>250]

In [547]:
df_672_min

,0,coord_list,coord_count
11,ENSG00000188976,"['AAACAGAGCGACTCCT-1', 'AAACAGGGTCTATATT-1', '...",551.0
16,ENSG00000188290,"['AAACAAGTATCTCCCA-1', 'AAACACCAATAACTGC-1', '...",781.0
17,ENSG00000187608,"['AAACAAGTATCTCCCA-1', 'AAACCGGGTAGGTACC-1', '...",1058.0
18,ENSG00000188157,"['AAACAAGTATCTCCCA-1', 'AAACCCGAACGAAATC-1', '...",647.0
26,ENSG00000078808,"['AAACAGAGCGACTCCT-1', 'AAACCGTTCGTCCAGG-1', '...",953.0
...,...,...,...
23449,ENSG00000198886,"['AAACAAGTATCTCCCA-1', 'AAACACCAATAACTGC-1', '...",4015.0
23450,ENSG00000198786,"['AAACAAGTATCTCCCA-1', 'AAACACCAATAACTGC-1', '...",3877.0
23451,ENSG00000198695,"['AAACCGGAAATGTTAA-1', 'AAACCGGGTAGGTACC-1', '...",1690.0
23452,ENSG00000198727,"['AAACAAGTATCTCCCA-1', 'AAACACCAATAACTGC-1', '...",4015.0
23460,ENSG00000278817,"['AAACCGGAAATGTTAA-1', 'AAACGACAGTCTTGCC-1', '...",620.0

In [548]:
df_507_min

,0,coord_list,coord_count
11,ENSG00000188976,"['AAACCTAAGCAGCCGG-1', 'AAACGAAGAACATACC-1', '...",435.0
16,ENSG00000188290,"['AAACATTTCCCGGATT-1', 'AAACGGGCGTACGGGT-1', '...",709.0
17,ENSG00000187608,"['AAACAACGAATAGTTC-1', 'AAACAAGTATCTCCCA-1', '...",1064.0
18,ENSG00000188157,"['AAACATTTCCCGGATT-1', 'AAACGGGCGTACGGGT-1', '...",534.0
26,ENSG00000078808,"['AAACAGGGTCTATATT-1', 'AAACCACTACACAGAT-1', '...",756.0
...,...,...,...
23449,ENSG00000198886,"['AAACAACGAATAGTTC-1', 'AAACAAGTATCTCCCA-1', '...",4226.0
23450,ENSG00000198786,"['AAACAAGTATCTCCCA-1', 'AAACAATCTACTAGCA-1', '...",4149.0
23451,ENSG00000198695,"['AAACACCAATAACTGC-1', 'AAACAGGGTCTATATT-1', '...",1242.0
23452,ENSG00000198727,"['AAACAACGAATAGTTC-1', 'AAACAAGTATCTCCCA-1', '...",4224.0
23460,ENSG00000278817,"['AAACAAGTATCTCCCA-1', 'AAACAGTGTTCCTGGG-1', '...",530.0

In [549]:
df_507_res = df_507_min.reset_index()
df_507_res

,index,0,coord_list,coord_count
0,11,ENSG00000188976,"['AAACCTAAGCAGCCGG-1', 'AAACGAAGAACATACC-1', '...",435.0
1,16,ENSG00000188290,"['AAACATTTCCCGGATT-1', 'AAACGGGCGTACGGGT-1', '...",709.0
2,17,ENSG00000187608,"['AAACAACGAATAGTTC-1', 'AAACAAGTATCTCCCA-1', '...",1064.0
3,18,ENSG00000188157,"['AAACATTTCCCGGATT-1', 'AAACGGGCGTACGGGT-1', '...",534.0
4,26,ENSG00000078808,"['AAACAGGGTCTATATT-1', 'AAACCACTACACAGAT-1', '...",756.0
...,...,...,...,...
6096,23449,ENSG00000198886,"['AAACAACGAATAGTTC-1', 'AAACAAGTATCTCCCA-1', '...",4226.0
6097,23450,ENSG00000198786,"['AAACAAGTATCTCCCA-1', 'AAACAATCTACTAGCA-1', '...",4149.0
6098,23451,ENSG00000198695,"['AAACACCAATAACTGC-1', 'AAACAGGGTCTATATT-1', '...",1242.0
6099,23452,ENSG00000198727,"['AAACAACGAATAGTTC-1', 'AAACAAGTATCTCCCA-1', '...",4224.0
6100,23460,ENSG00000278817,"['AAACAAGTATCTCCCA-1', 'AAACAGTGTTCCTGGG-1', '...",530.0

In [550]:
max_row_indices = df_507_res['coord_count'].idxmax()
max_row_indices

6089

In [451]:
df_res.loc[max_row_indices]

index                                                      23440
0                                                ENSG00000198888
coord_list     ['AAACAAGTATCTCCCA-1', 'AAACAATCTACTAGCA-1', '...
coord_count                                               3639.0
Name: 8090, dtype: object

In [525]:
df_672_res.loc[0,0]

'ENSG00000188976'

<h5> from coordinate list into 2D matrix

In [551]:
# for i in range(len(df_res)):

directory = 'datapoints/151507/'

for i in range(len(df_507_res)):

    # get coord_list from dataframe as string back to list
    my_list = ast.literal_eval(df_507_res.loc[i,'coord_list'])

    # table for converting coordinate list into actual pixel coordinates
    ext_coord = coord507.loc[my_list]

    # points = coord673.values.tolist()
    # sites = coord673.index.tolist()
    points = ext_coord.values.tolist()
    sites = ext_coord.index.tolist()
    
    x, y = zip(*points)
    
    # Convert into 2D matrix
    x_resolution = 200
    y_resolution = 250

    x_min = min(x)
    x_max = max(x)
    x_ptp = x_max - x_min

    y_min = min(y)
    y_max = max(y)
    y_ptp = y_max - y_min

    img = np.zeros((y_resolution+20, x_resolution+20), dtype=bool)

    for k, l in points:
        x_pxl = (k - x_min) / x_ptp * x_resolution
        y_pxl = (l - y_min) / y_ptp * y_resolution
        img[int(y_pxl+10), int(x_pxl+10)] = 1
    
    np.save(directory+df_507_res.loc[i,0]+'.npy',img)

In [465]:
# for i in range(len(points)):
#     for j in range(len(points[i])):
#         points[i][j] = points[i][j] * 0.02
# points[0:4]

In [466]:
# x, y = zip(*points)

In [467]:
# print(points[0],x[0],y[0])

[9791.0, 8468.0] 9791.0 8468.0

In [552]:
# for i, filename in enumerate(os.listdir('datapoints/151673')):
#     print(filename)
directory = 'datapoints/151507'
len(os.listdir(directory))

6101

In [553]:
filenames = os.listdir(directory)
filenames[:3]

['ENSG00000137168.npy', 'ENSG00000139168.npy', 'ENSG00000072518.npy']

In [ ]:
plt.figure(figsize=(8,10))

fig, ax = plt.subplots(3,1,figsize=(12,36))

for i, filename in enumerate(filenames[:3]) :
    if filename.endswith('.npy') and os.path.isfile(os.path.join(directory, filename)):
        new_test = np.load(directory+'/'+filename)   
        ax[i].imshow(new_test, cmap='viridis',origin='lower')

plt.show()

In [ ]:
# 2D matrix are formed, but seems to be too sparse to be learned need to rescale
plt.figure(figsize=(8,10))

fig, ax = plt.subplots(figsize=(8,10))
ax.imshow(img, cmap='viridis',origin='lower')
plt.savefig('plot.png')
plt.show()

In [ ]:
# 2D matrix are formed, but seems to be too sparse to be learned need to rescale
plt.figure(figsize=(8,10))

fig, ax = plt.subplots(figsize=(8,10))
ax.imshow(img, cmap='viridis',origin='lower')
# plt.savefig('plot.png')
plt.show()

In [ ]:
plt.figure(figsize=(8,10))
plt.scatter(x,y,s=5,c='b')
plt.show()

In [202]:
len(sites)

3639

<h1>Feed to NN

In [ ]:
# NN take matrix of gene distribution

# make into tensor

# run NN model

# output should be decoder part of hidden features

In [ ]:
os.environ["CUDA_VISIBLE_DEVICES"]="1"
train_root_path = '/home/Spatial_transcriptomic/VERIFY/train' 
test_root_path = '/home/Spatial_transcriptomic/VERIFY/test'
batch_size = 300
epochs = 200
learning_rate = 1e-3
im_size = size_10
# torch.manual_seed(42)

In [ ]:
instance_X_train, instance_X_test = train_test_split(instance_imgs_10, test_size=0.20, random_state=42,shuffle=True) 


train_dataset = TumorDatasetTrain(instance=instance_X_train, root_dir=train_root_path,
                                transform=transforms.Compose([ToTensor()]))
test_dataset = TumorDatasetTest(instance=instance_X_test, root_dir=test_root_path, 
                                transform=transforms.Compose([ToTensor()]))
all_dataset = TumorDatasetAll(instance=instance_imgs_10, root_dir=train_root_path,
                                transform=transforms.Compose([ToTensor()]))

dataloader_all = DataLoader(all_dataset, batch_size=batch_size, shuffle=True, num_workers=1)
dataloader_train = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=1)
dataloader_test = DataLoader(test_dataset, batch_size=batch_size, shuffle=True, num_workers=1)

running_loss = []
running_vloss = []

In [ ]:
model_path1 = "/home/Spatial_transcriptomic/VERIFY/lab06_AE_weight_decay.pth"
save = False
pret = False

In [ ]:
#  use gpu if available
start_time1 = time.time()

device = torch.device("cuda")

# create a model from `AE` autoencoder class
# load it to the specified device, either gpu or cpu
# model = ConvAutoencoder().to(device)
model = AE(input_shape=im_size*im_size*33).to(device)
model.double()

# create an optimizer object
# Adam optimizer with learning rate 1e-3
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# mean-squared error loss
criterion = nn.MSELoss()
running_loss = []
running_vloss = []

#     Auto Encoder Training
print('Training AE')
if (not os.path.exists(model_path1) or not pret):
    for epoch in range(epochs):
        start_time = time.time()
        loss = 0
        vloss = 0
        model.train()
        for batch_ndx, batch_features in enumerate(dataloader_train):
            # reshape mini-batch data to [N, 784] matrix
            # load it to the active device
    #             batch_features = Variable(batch_features['image']).to(device)
    #             batch_features = batch_features.type(torch.cuda.FloatTensor)
            images = Variable(batch_features['image']).view(-1,im_size*im_size*33).to(device)
    #             images = images.type(torch.cuda.FloatTensor)
            # reset the gradients back to zero
            # PyTorch accumulates gradients on subsequent backward passes
            optimizer.zero_grad()

            # compute reconstructions
            outputs, coded = model(images)
#             print('size', outputs.size(), coded.size())
    #             encoder_only_nosig = model.encoder(images)
    #             encoder_only = torch.sigmoid(model.encoder(images))
            # compute training reconstruction loss
            train_loss = criterion(outputs, images)

            # compute accumulated gradients
            train_loss.backward()

            # perform parameter update based on current gradients
            optimizer.step()
            # add the mini-batch training loss to epoch loss
            loss += train_loss.item()

        # compute the epoch training loss
        loss = loss / len(dataloader_train)
        running_loss.append(loss)
        # display the epoch training loss
        #if(epoch % 5 == 0):
    #       ------------------------------------------------------------------------  
        model.eval()
        with torch.no_grad():
            for batch_ndx, batch_features in enumerate(dataloader_test):
                # reshape mini-batch data to [N, 784] matrix
                # load it to the active device
    #             batch_features = Variable(batch_features['image']).to(device)
    #             batch_features = batch_features.type(torch.cuda.FloatTensor)
                images = Variable(batch_features['image']).view(-1,im_size*im_size*33).to(device)
    #                 images = images.type(torch.cuda.FloatTensor)
                # reset the gradients back to zero
                # PyTorch accumulates gradients on subsequent backward passes
                optimizer.zero_grad()

                # compute reconstructions
                outputs, coded = model(images)
    #             encoder_only_nosig = model.encoder(images)
    #             encoder_only = torch.sigmoid(model.encoder(images))
                # compute training reconstruction loss
                valid_loss = criterion(outputs, images)

                # perform parameter update based on current gradients
    #                 optimizer.step()
                # add the mini-batch training loss to epoch loss
                vloss += valid_loss.item()

            # compute the epoch training loss
            vloss = vloss / len(dataloader_test)
            running_vloss.append(vloss)

    #     -----------------------------------------------------------------------------
        current_time = time.time()
        elapsed_time = current_time - start_time
        print("epoch : {}/{}, recon loss = {:.8f}, valid loss = {:.8f}, time = {:.2f}s".format(epoch + 1, epochs, loss, vloss, elapsed_time))


        if (epoch > 3) and (abs(running_vloss[epoch] - running_vloss[epoch-1]) <= 0.0001) and (abs(running_vloss[epoch - 1] - running_vloss[epoch - 2]) <= 0.0001):
            print('satisfied early stop')
            break
    if save:
        torch.save(model.state_dict(), model_path1)

In [123]:
coord_list = [[1.2, 3.4], [2.3, 4.5], [3.4, 5.6], [4.5, 6.7]]

# convert the list to a PyTorch tensor
coords = torch.tensor(coord_list)

# reshape the tensor to the required input shape (batch size, number of channels, height, width)
coords = coords.view(1, 1, -1, 2)

In [124]:
coords

tensor([[[[1.2000, 3.4000],
          [2.3000, 4.5000],
          [3.4000, 5.6000],
          [4.5000, 6.7000]]]])

<h1>Run BEER

In [ ]:
# get decoder hidden feature and concatenate with assays

# final matrix includes ~100 extra features of spatial embeddings treated as spots

# BEER should results in a Umap plot, Correlation plot, and no-Batch effect umap